input_dir: ""
results_dir: ""

operating_system: "linux"
forward_tag: "R1"
reverse_tag: "R2"
nanopore_tag: "nanopore"
nanopore_pooled: False
nanopore_pooled_name: "raw"
long_assembler: "canu"

trimmomatic_leading: "20"
trimmomatic_trailing: "20"
trimmomatic_window_size: "4"
trimmomatic_window_quality: "20"
trimmomatic_minlen: "50"
nanopore_quality: "10"
sampling: "sub tot"

representative_contigs: ""
sra_list: ""

#species
p_ident: "95"

#Count Unique
kmer_window: "25000"

#bbnorm
min_norm: "0"
max_norm: "100"
max_subsample: "20000000"
#Spades and canu assembly
min_len: "1000"
min_cov: "2"

contaminants_list: ""
adapters_file: "adapters.fa"
additional_reference_contigs: ""
basecalled_dir: "data/basecalled/"

img_vr_db: "db/IMG_VR/"
virSorter_db: "db/VirSorter/virsorter-data"
#raken_db: "db/NCBI-bacteria-01.04.2019"
kraken_db: "db/KRAKEN"
kraken_db_human: "db/kraken2_human_db"
kraken_tools: "tools/KrakenTools"

checkv_db: "db/checkv-db-v0.6"
canu_dir: "tools/canu-2.0/Linux-amd64/bin" #linux
quast_dir: "tools/quast-5.0.2"
virSorter_dir: "tools/VirSorter"
WTP_dir: "tools/WTP"
virFinder_dir: "tools/VirFinder"
clusterONE_dir: "tools/clusterONE"
vcontact_dir: "tools/vcontact2"
taxonomy_file: "db/vcontact2/formatting_taxonomy_affiliations.csv"
mmseqs_dir: "tools/MMseqs2"
viga_dir: "tools/viga"
piler_dir: "tools/pilercr1.06"
trf_dir: "tools/TRF"
vibrant_dir: "tools/VIBRANT"
sra_toolkit_dir: "tools/sratoolkit.2.10.0-ubuntu64"
ALE_dir: "tools/ALE"
wish_dir: "tools/WIsH"
